services:
  web:
    build: .
    command: flask run --host 0.0.0.0 --port 3000
    hostname: weather-report
    ports:
    - 3000:3000
    volumes:
      - .:/app
  mongo:
    image: mongo:latest
    hostname: database
    ports:
    - 27017:27017
    volumes:
      - ./db:/data/db
  client:
    build: .
    volumes:
      - .:/app
    command: python3 src/client.py
